[build-system]
requires = [
    "setuptools>=51.0.0",
    "wheel",
    "scipy>=1.9.1",
    "numpy>=1.22.0",
    "matplotlib>=3.4.3",
]

[tool.black]
line-length = 79
target-version = ["py37", "py38", "py39"]
experimental_string_processing = true

[tool.isort]
profile = "black"
line_length = 79
