[build-system]
requires = [
    "setuptools>=51.0.0",
    "wheel",
    "scipy>=1.6.2",
    "numpy>=1.20.1",
    "matplotlib>=3.4.2",
]

[tool.black]
line-length = 79
target-version = ["py37", "py38", "py39"]
experimental_string_processing = true

[tool.isort]
profile = "black"
line_length = 79
