name: Upload Python Package

on:
  push:
    tags:
      - 'v*'
    
permissions:
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - run: |
          python -m pip install --upgrade pip
          pip install build --user
      - run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
    
