name: import-formatter
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install isort (with requirements.txt support)
        run: pip install isort[requirements_deprecated_finder]
      - name: run isort --check
        run: isort --check .
      - name: commit changes to push, if needed
        if: failure()
        run: |
          isort .
          git config --global user.name 'autoisort'
          git config --global user.email 'autoisort@users.noreply.github.com'
          # git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git commit -am "fixup: format imports with isort"
          git push # --force orgin HEAD:$GITHUB_REF
